version: '3.9'

services:
  client-service:
    build: ./services/client-service
    container_name: client-service
    ports:
      - '8000:8000'
    env_file: .env
    networks:
      - microbank-network

  banking-service:
    build: ./services/banking-service
    container_name: banking-service
    ports:
      - '8001:8001'
    env_file: .env
    networks:
      - microbank-network

  client:
    build: ./client
    container_name: client
    ports:
      - '3000:3000'
    env_file: .env
    depends_on:
      - client-service
      - banking-service
    networks:
      - microbank-network

networks:
  microbank-network:
    driver: bridge
