version: '3.9'

services:
  db:
    image: postgres:15
    container_name: microbank-db
    environment:
      POSTGRES_DB: microbank
      POSTGRES_USER: microbank
      POSTGRES_PASSWORD: microbank123
    ports:
      - '5432:5432'
    networks:
      - microbank-network
  client-service:
    build: ./services/client-service
    container_name: client-service
    ports:
      - '8000:8000'
    depends_on:
      - db
    env_file: .env
    networks:
      - microbank-network
    command: sh -c "python manage.py migrate && python manage.py seed_admin && gunicorn client_service.wsgi:application --bind 0.0.0.0:8000 --workers 3"

  banking-service:
    build: ./services/banking-service
    container_name: banking-service
    ports:
      - '8001:8001'
    depends_on:
      - db
    env_file: .env
    networks:
      - microbank-network

  client:
    build: ./client
    container_name: client
    ports:
      - '3000:3000'
    env_file: .env
    depends_on:
      - client-service
      - banking-service
    networks:
      - microbank-network

networks:
  microbank-network:
    driver: bridge
