version: '3.9'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS:-guest}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_VHOST:-/}
    healthcheck:
      test: ['CMD', 'rabbitmq-diagnostics', 'check_running']
      interval: 5s
      timeout: 5s
      retries: 20

  client-service:
    build: ./services/client-service
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - INTERNAL_TOKEN=${INTERNAL_TOKEN}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASS=${RABBITMQ_PASS}
      - RABBITMQ_VHOST=${RABBITMQ_VHOST}
      - CLIENT_SERVICE_URL=${CLIENT_SERVICE_URL}
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
      - static_volume:/app/staticfiles
    depends_on:
      rabbitmq:
        condition: service_healthy
    ports:
      - '8001:8000'

  banking-service:
    build: ./services/banking-service
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - INTERNAL_TOKEN=${INTERNAL_TOKEN}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASS=${RABBITMQ_PASS}
      - RABBITMQ_VHOST=${RABBITMQ_VHOST}
      - CLIENT_SERVICE_URL=${CLIENT_SERVICE_URL}
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
      - static_volume:/app/staticfiles
    depends_on:
      rabbitmq:
        condition: service_healthy
    ports:
      - '8002:8000'

  nginx:
    build: ./nginx
    ports:
      - '8080:8080'
    environment:
      - INTERNAL_TOKEN=${INTERNAL_TOKEN}
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/staticfiles
    depends_on:
      client-service:
        condition: service_started
      banking-service:
        condition: service_started
    command:
      [
        '/bin/sh',
        '-c',
        "chmod +x /wait-for-it.sh && /wait-for-it.sh http://client-service:8000/health/ http://banking-service:8000/health/ -- nginx -g 'daemon off;'",
      ]

  web-client:
    build: ./client
    environment:
      - NEXT_PUBLIC_API_BASE=${NEXT_PUBLIC_API_BASE}
    ports:
      - '3000:3000'
    depends_on:
      - nginx

volumes:
  client_db:
  banking_db:
  static_volume:
